services:
  webserver:
    image: nginx:alpine
    restart: unless-stopped

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./main_website:/usr/share/nginx/html/main_website:ro
      - ./sub_website:/usr/share/nginx/html/sub_website:ro

    networks:
      - dokploy-network

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"

      # ROOT
      - "traefik.http.routers.puvistoreable.rule=Host(`puvistoreable.web.id`)"
      - "traefik.http.routers.puvistoreable.entrypoints=web"
      - "traefik.http.routers.puvistoreable.service=puvistoreable"

      # WILDCARD
      - "traefik.http.routers.puvistoreable-wildcard.rule=HostRegexp(`^.+\\.puvistoreable\\.web\\.id$`)"
      - "traefik.http.routers.puvistoreable-wildcard.entrypoints=web"
      - "traefik.http.routers.puvistoreable-wildcard.service=puvistoreable"

      # SERVICE
      - "traefik.http.services.puvistoreable.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
