# ==========================================
# ROOT DOMAIN
# ==========================================
server {
    listen 80;
    listen [::]:80;

    server_name puvistoreable.web.id;

    root /usr/share/nginx/html/main_website;
    index index.html;

    location / {
        try_files $uri $uri/ @sub_website;
    }

    location @sub_website {
        root /usr/share/nginx/html/sub_website;
        try_files $uri $uri/ =404;
    }
}


# ==========================================
# SUBDOMAIN | ABCDEFMAS:D
# ==========================================
server {
    listen 80;
    listen [::]:80;

    server_name subdomainabc;

    root /usr/share/nginx/html/sub_website/folderapaja;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
